#ifndef __INCL_FONTDEF__
#define __INCL_FONTDEF__

// #define LCDFONT_INCLUDE_FONT_5x7
#define LCDFONT_INCLUDE_FONT_6x8
//#define LCDFONT_INCLUDE_FONT_6x12
//#define LCDFONT_INCLUDE_FONT_8x8
//#define LCDFONT_INCLUDE_FONT_8x12N
//#define LCDFONT_INCLUDE_FONT_8x16

// #define LCDFONT_INCLUDE_FONT_7x10
// #define LCDFONT_INCLUDE_FONT_11x18
// #define LCDFONT_INCLUDE_FONT_16x26
// #define LCDFONT_INCLUDE_FONT_16x16N
// #define LCDFONT_INCLUDE_FONT_16x24N
// #define LCDFONT_INCLUDE_FONT_16x24
// #define LCDFONT_INCLUDE_FONT_12x24
// #define LCDFONT_INCLUDE_FONT_12x16N
// #define LCDFONT_INCLUDE_FONT_12x16AVW
// #define LCDFONT_INCLUDE_FONT_12x21N
// #define LCDFONT_INCLUDE_FONT_16x32

#define USE_GEOMETRIC 0

//#define deffont Font_6x8

#endif
